eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka

server:
  port: 8188

spring:
  application:
    name: consumer
  zipkin:
    base-url: http://localhost:8080
    sender:
      type: web
feign:
  hystrix:
    enabled: true