eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka

server:
  port: 8288

spring:
  application:
    name: zuul
zuul:
  routes:
    user:
      path: /user/**
      serviceId: provider
