spring:
  application:
    name: provider
  zipkin:
    base-url: http://localhost:8080
    sender:
      type: web
server:
  port: 8088
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
    instance-info-replication-interval-seconds: 30